# Generated by Django 4.1 on 2022-12-14 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stonelib', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model3d',
            name='Inscription',
            field=models.ForeignKey(blank=True, db_column='Inscription_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='stonelib.inscription'),
        ),
    ]
