# Generated by Django 4.1 on 2023-02-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stonelib', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model3d',
            name='FrameCount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='model3d',
            name='PolygonCM',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='model3d',
            name='PolygonCount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='museum',
            name='Docnumber',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='museum',
            name='LAT',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='museum',
            name='LON',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='museum',
            name='Link',
            field=models.URLField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='site',
            name='YearExcavate',
            field=models.IntegerField(null=True),
        ),
    ]
