# Generated by Django 3.2.15 on 2023-06-06 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stonelib', '0002_alter_model3d_framecount_alter_model3d_polygoncm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='BitigKz',
            field=models.URLField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='image',
            name='AdditionalDescription',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='ID',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='Inscription',
            field=models.ForeignKey(blank=True, db_column='Inscription_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='stonelib.inscription'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='Site',
            field=models.ForeignKey(blank=True, db_column='Site_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscriptions', to='stonelib.site'),
        ),
        migrations.AlterField(
            model_name='model3d',
            name='Inscription',
            field=models.ForeignKey(blank=True, db_column='Inscription_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='models', to='stonelib.inscription'),
        ),
        migrations.AlterField(
            model_name='model3d',
            name='PolygonCount',
            field=models.FloatField(null=True),
        ),
    ]
