# Generated by Django 4.1 on 2022-12-23 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stonelib', '0002_alter_model3d_inscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='Site',
            field=models.ForeignKey(blank=True, db_column='Site_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sites', to='stonelib.site'),
        ),
    ]
