# Generated by Django 3.2.15 on 2023-06-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stonelib', '0003_auto_20230606_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='CitBazylhan',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='CitDTS',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='CitKormushin',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='CitVasilev',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='DigitalDocumentation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='LAT',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='LON',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='NameVariations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='FirstNotion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='LAT',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='LON',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='NamePerson',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='NameVariations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='YearExcavate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
