# Generated by Django 3.2.15 on 2023-06-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stonelib', '0004_auto_20230606_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='Link',
        ),
        migrations.RemoveField(
            model_name='model3d',
            name='Link',
        ),
        migrations.RemoveField(
            model_name='museum',
            name='Dates',
        ),
        migrations.RemoveField(
            model_name='museum',
            name='Docnumber',
        ),
        migrations.AddField(
            model_name='model3d',
            name='ModelProcesser',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='model3d',
            name='Photographer',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='ContextType',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='model3d',
            name='FrameCount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='model3d',
            name='Object',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='model3d',
            name='PolygonCM',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='model3d',
            name='PolygonCount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='museum',
            name='Adress',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='museum',
            name='LAT',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='museum',
            name='LON',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='Area',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='Country',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='Region',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='Type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
