# Generated by Django 3.2.15 on 2023-06-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stonelib', '0005_auto_20230609_1153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model3d',
            old_name='PolygonCM',
            new_name='AreaCM',
        ),
        migrations.RenameField(
            model_name='model3d',
            old_name='PolygonCount',
            new_name='PolygonCountGeneral',
        ),
        migrations.AddField(
            model_name='model3d',
            name='PolygonCountMaster',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
